allowBuilds:
  '@db-ux/db-theme': true
  '@db-ux/db-theme-fonts': true
  '@db-ux/db-theme-icons': true
  '@db-ux/db-theme-illustrative-icons': true
  esbuild: true
  sharp: false

minimumReleaseAgeExclude:
  - "@db-ux/db-theme"
  - "@db-ux/db-theme-fonts"
  - "@db-ux/db-theme-icons"
  - "@db-ux/db-theme-illustrative-icons"
  - '@db-ux/agent-cli@5.2.1-shell2-b3d6ca4'
  - '@db-ux/core-components@5.2.1-shell2-b3d6ca4'
  - '@db-ux/core-eslint-plugin@5.2.1-shell2-b3d6ca4'
  - '@db-ux/core-foundations@5.2.1-shell2-b3d6ca4'
  - '@db-ux/core-stylelint@5.2.1-shell2-b3d6ca4'
  - '@db-ux/react-core-components@5.2.1-shell2-b3d6ca4'
