allowBuilds:
  '@db-ux/db-theme': true
  '@db-ux/db-theme-fonts': true
  '@db-ux/db-theme-icons': true
  '@db-ux/db-theme-illustrative-icons': true
  esbuild: true
  sharp: false

minimumReleaseAgeExclude:
  - "@db-ux/db-theme"
  - "@db-ux/db-theme-fonts"
  - "@db-ux/db-theme-icons"
  - "@db-ux/db-theme-illustrative-icons"
  - "@db-ux/agent-cli"
  - "@db-ux/core-components"
  - "@db-ux/core-eslint-plugin"
  - "@db-ux/core-foundations"
  - "@db-ux/core-stylelint"
  - "@db-ux/react-core-components"
