export const buttonConfig = {
	component: 'DBButton',
	elementId: 'demo-button',
	textElementId: 'button-text',
	defaultText: 'Text',
	defaultProps: {
		size: 'medium',
		variant: 'outlined',
	},
	slots: [{ name: 'children', description: 'default slot' }],
	events: [{ name: 'click / onClick', type: '---' }],
	properties: [
		// Content
		{
			name: 'text',
			type: 'text',
			label: 'Text',
			description: 'Alternative for default slot/children.',
			defaultValue: 'Text',
			showInPlayground: true,
			dependsOn: { prop: 'no-text', value: 'false' },
		},
		// Appearance
		{
			name: 'variant',
			type: 'select',
			label: 'Variant',
			description: 'Variant of the button.',
			defaultValue: 'outlined',
			showInPlayground: true,
			options: [
				{ value: 'outlined', label: 'Outlined', default: true },
				{ value: 'brand', label: 'Brand' },
				{ value: 'filled', label: 'Filled' },
				{ value: 'ghost', label: 'Ghost' },
			],
		},
		{
			name: 'size',
			type: 'select',
			label: 'Size',
			description: 'The size attribute changes the font-size and other related sizes.',
			defaultValue: 'medium',
			showInPlayground: true,
			options: [
				{ value: 'small', label: 'Small' },
				{ value: 'medium', label: 'Medium', default: true },
			],
		},
		{
			name: 'width',
			type: 'select',
			label: 'Width',
			description: 'Width of the component.',
			defaultValue: 'auto',
			showInPlayground: true,
			options: [
				{ value: 'auto', label: 'Auto', default: true },
				{ value: 'full', label: 'Full' },
			],
		},
		// No Text toggle
		{
			name: 'no-text',
			alternativeName: 'noText',
			type: 'checkbox',
			label: 'No Text',
			description: 'Hide text, show icon only.',
			defaultValue: false,
			showInPlayground: true,
		},
		// Show Icon Leading toggle (text mode only)
		{
			name: 'show-icon',
			alternativeName: 'showIcon',
			type: 'checkbox',
			label: 'Show Icon Leading',
			description: 'Enables the leading icon.',
			defaultValue: false,
			showInPlayground: true,
			dependsOn: { prop: 'no-text', value: 'false' },
		},
		// Icon Leading — visible when no-text OR show-icon is on
		// Label changes to "Icon" when no-text is active
		{
			name: 'icon-leading',
			alternativeName: 'iconLeading',
			type: 'text',
			label: 'Icon Leading',
			description: 'Icon identifier for the leading icon.',
			defaultValue: 'x_placeholder',
			showInPlayground: true,
			dependsOn: 'show-icon',
			labelWhen: { condition: { prop: 'no-text', value: 'true' }, label: 'Icon' },
		},
		// Trailing icon (text mode only)
		{
			name: 'show-icon-trailing',
			alternativeName: 'showIconTrailing',
			type: 'checkbox',
			label: 'Show Icon Trailing',
			description: 'Enables the trailing icon.',
			defaultValue: false,
			showInPlayground: true,
			dependsOn: { prop: 'no-text', value: 'false' },
		},
		{
			name: 'icon-trailing',
			alternativeName: 'iconTrailing',
			type: 'text',
			label: 'Icon Trailing',
			description: 'Icon identifier for the trailing icon.',
			defaultValue: 'x_placeholder',
			showInPlayground: true,
			dependsOn: 'show-icon-trailing',
		},
		// States
		{
			name: 'disabled',
			type: 'checkbox',
			label: 'Disabled',
			description: 'Disables the button.',
			defaultValue: false,
			showInPlayground: true,
		},
		// Hidden properties
		{
			name: 'icon',
			type: 'text',
			label: 'Icon',
			defaultValue: '',
			showInPlayground: false,
			description: 'Define an icon by its identifier.',
		},
		{
			name: 'type',
			type: 'select',
			label: 'Type',
			description: 'The type attribute specifies the type of button.',
			defaultValue: 'button',
			showInPlayground: false,
			options: [
				{ value: 'button', label: 'Button', default: true },
				{ value: 'submit', label: 'Submit' },
				{ value: 'reset', label: 'Reset' },
			],
		},
		{
			name: 'show-icon-leading',
			alternativeName: 'showIconLeading',
			type: 'checkbox',
			label: 'Show Icon Leading',
			defaultValue: false,
			showInPlayground: false,
			description: 'Enables or disables the visibility of the leading icon.',
		},
		{
			name: 'id',
			type: 'text',
			label: 'ID',
			defaultValue: '',
			showInPlayground: false,
			description: 'ID of the component.',
		},
		{
			name: 'className',
			type: 'text',
			label: 'Class Name',
			defaultValue: '',
			showInPlayground: false,
			description: 'React className.',
		},
		{
			name: 'name',
			type: 'text',
			label: 'Name',
			defaultValue: '',
			showInPlayground: false,
			description: 'Name attribute.',
		},
		{
			name: 'form',
			type: 'text',
			label: 'Form',
			defaultValue: '',
			showInPlayground: false,
			description: 'Associates with a form element.',
		},
		{
			name: 'value',
			type: 'text',
			label: 'Value',
			defaultValue: '',
			showInPlayground: false,
			description: 'Initial value.',
		},
	],
};
