export const customSelectConfig = {
	elementId: 'demo-custom-select',
	defaultText: 'Placeholder',
	defaultProps: {
		id: 'demo-custom-select',
		label: 'Label',
		placeholder: 'Placeholder',
	},
	slots: [
		{
			name: 'children',
			description: 'default slot',
		},
	],
	events: [
		{
			name: 'amountChange / onAmountChange',
			type: '---',
		},
		{
			name: 'dropdownToggle / onDropdownToggle',
			type: '---',
		},
		{
			name: 'optionSelected / onOptionSelected',
			type: '---',
		},
		{
			name: 'search / onSearch',
			type: '---',
		},
	],
	properties: [
		{
			name: 'id',
			label: 'ID',
			type: 'text',
			defaultValue: '',
			description:
				'ID of the component, generated automatically for some components as a fallback if unset.',
			showInPlayground: false,
		},
		{
			name: 'invalid-message / invalidMessage',
			label: 'Invalid Message',
			type: 'text',
			defaultValue: '',
			description: 'Helper message for invalid form components',
			showInPlayground: false,
		},
		{
			name: 'message',
			label: 'Message',
			type: 'text',
			defaultValue: '',
			description: 'Optional helper message for form components',
			showInPlayground: false,
		},
		{
			name: 'show-message / showMessage',
			label: 'Show Message',
			type: 'text',
			defaultValue: '',
			description: 'Enables or disables the visibility of the message.',
			showInPlayground: false,
		},
		{
			name: 'aria-described-by / ariaDescribedBy',
			label: 'Aria Described By',
			type: 'text',
			defaultValue: '',
			description: 'Overwrites auto handling for aria-describedby.',
			showInPlayground: false,
		},
		{
			name: 'show-no-results / showNoResults',
			label: 'Show No Results',
			type: 'checkbox',
			defaultValue: false,
			description: 'Dropdown - enable no options infotext',
			showInPlayground: false,
		},
		{
			name: 'show-loading / showLoading',
			label: 'Show Loading',
			type: 'checkbox',
			defaultValue: false,
			description: 'Dropdown - enable loading infotext and spinner',
			showInPlayground: false,
		},
		{
			name: 'multiple',
			label: 'Multiple',
			type: 'checkbox',
			defaultValue: false,
			description: 'Enables CustomSelect',
			showInPlayground: false,
		},
		{
			name: 'show-select-all / showSelectAll',
			label: 'Show Select All',
			type: 'checkbox',
			defaultValue: false,
			description: 'Forces select all checkbox (only for multiple).',
			showInPlayground: false,
		},
		{
			name: 'show-search / showSearch',
			label: 'Show Search',
			type: 'checkbox',
			defaultValue: false,
			description: 'Forces search in header.',
			showInPlayground: false,
		},
		{
			name: 'values',
			label: 'Values',
			type: 'text',
			defaultValue: '',
			description: 'Initial value for multi select',
			showInPlayground: false,
		},
		{
			name: 'validation',
			label: 'Validation',
			type: 'select',
			defaultValue: 'no-validation',
			description:
				'Marks an input element as invalid (red) / valid (green) / no-validation (grey). Overwrites the :user-valid selector.',
			options: [
				{ value: 'invalid', label: 'Invalid' },
				{ value: 'valid', label: 'Valid' },
				{ value: 'no-validation', label: 'No Validation', default: true },
			],
			showInPlayground: true,
		},
		{
			name: 'options',
			label: 'Options',
			type: 'text',
			defaultValue: '',
			description: 'You should pass in the options as an array.',
			showInPlayground: false,
		},
		{
			name: 'search-value / searchValue',
			label: 'Search Value',
			type: 'text',
			defaultValue: '',
			description: 'Optional: Prefill the value of the search input',
			showInPlayground: false,
		},
		{
			name: 'selected-labels / selectedLabels',
			label: 'Selected Labels',
			type: 'text',
			defaultValue: '',
			description:
				'Optional: If you want to show a custom label for the selected values. You need to define the empty state as well based on selected options.',
			showInPlayground: false,
		},
		{
			name: 'selected-type / selectedType',
			label: 'Selected Type',
			type: 'select',
			defaultValue: 'text',
			description: 'Change the selected type for values shown in multi select',
			options: [
				{ value: 'amount', label: 'Amount' },
				{ value: 'text', label: 'Text', default: true },
				{ value: 'tag', label: 'Tag' },
			],
			showInPlayground: false,
		},
		{
			name: 'amount-text / amountText',
			label: 'Amount Text',
			type: 'text',
			defaultValue: '',
			description: 'Optional: if select-type="amount" change the shown text',
			showInPlayground: false,
		},
		{
			name: 'valid-message / validMessage',
			label: 'Valid Message',
			type: 'text',
			defaultValue: '',
			description: 'Helper message for valid form components',
			showInPlayground: false,
		},
		{
			name: 'required',
			label: 'Required',
			type: 'checkbox',
			defaultValue: false,
			description:
				"When the required attribute specified, the user will be required to fill the form element before submitting the form. The form element will be marked semantically as required and by default also visually with an asterisk '*' next to the label (unless the property showRequiredAsterisk is also set with the value false).",
			showInPlayground: false,
		},
		{
			name: 'select-all-label / selectAllLabel',
			label: 'Select All Label',
			type: 'text',
			defaultValue: '',
			description: 'Select all checkbox label',
			showInPlayground: false,
		},
		{
			name: 'remove-tags-texts / removeTagsTexts',
			label: 'Remove Tags Texts',
			type: 'text',
			defaultValue: '',
			description:
				'Optional: if you use selectedType=tag and options, you need to set the removeTagsTexts for screen reader users',
			showInPlayground: false,
		},
		{
			name: 'placement',
			label: 'Placement',
			type: 'select',
			defaultValue: 'bottom',
			description:
				'The placement attributes values change the position to absolute and adds a transform based on the placement.',
			options: [
				{ value: 'top', label: 'Top' },
				{ value: 'bottom', label: 'Bottom', default: true },
				{ value: 'top-start', label: 'Top Start' },
				{ value: 'top-end', label: 'Top End' },
				{ value: 'bottom-start', label: 'Bottom Start' },
				{ value: 'bottom-end', label: 'Bottom End' },
			],
			showInPlayground: false,
		},
		{
			name: 'className',
			label: 'Class Name',
			type: 'text',
			defaultValue: '',
			description: 'React specific for adding className to the component.',
			showInPlayground: false,
		},
		{
			name: 'form-field-width / formFieldWidth',
			label: 'Form Field Width',
			type: 'select',
			defaultValue: 'full',
			description:
				'Width of the component. Auto width based on children size, full width based on parent elements width.',
			options: [
				{ value: 'full', label: 'Full', default: true },
				{ value: 'auto', label: 'Auto' },
			],
			showInPlayground: false,
		},
		{
			name: 'variant',
			label: 'Variant',
			type: 'select',
			defaultValue: 'above',
			description: 'Change the variant of the label to float or hidden',
			options: [
				{ value: 'above', label: 'Above', default: true },
				{ value: 'floating', label: 'Floating' },
			],
			showInPlayground: true,
		},
		{
			name: 'show-required-asterisk / showRequiredAsterisk',
			label: 'Show Required Asterisk',
			type: 'checkbox',
			defaultValue: true,
			description:
				"This attribute allows to specify whether a form field which is marked as required will show a visual indicator (an asterisk '*'). It allows to prevent adding the visual indicator but still keep the field semantically required by setting its value to false. By default, its value is true, so the asterisk is shown when required is set.",
			showInPlayground: false,
		},
		{
			name: 'show-label / showLabel',
			label: 'Show Label',
			type: 'checkbox',
			defaultValue: true,
			description: 'Enables/disables the visibility of the label',
			showInPlayground: false,
		},
		{
			name: 'icon',
			label: 'Icon',
			type: 'text',
			defaultValue: '',
			description:
				'Define an icon by its identifier (like e.g. user, compare to Icons) to get displayed in front of the elements content.',
			showInPlayground: false,
		},
		{
			name: 'show-icon / showIcon',
			label: 'Show Icon',
			type: 'checkbox',
			defaultValue: false,
			description:
				'Enables or disables the visibility of the icon. The default value depends on the component. For many components this property is optional to reflect Figma properties.',
			showInPlayground: false,
		},
		{
			name: 'label',
			label: 'Label',
			type: 'text',
			defaultValue: 'Label',
			description: 'The label attribute specifies the caption of the form element.',
			showInPlayground: true,
		},
		{
			name: 'form',
			label: 'Form',
			type: 'text',
			defaultValue: '',
			description: 'Associates the control with a form element',
			showInPlayground: false,
		},
		{
			name: 'name',
			label: 'Name',
			type: 'text',
			defaultValue: '',
			description:
				"The name attribute gives the name of the form control, as used in form submission and in the form element's elements object.",
			showInPlayground: false,
		},
		{
			name: 'disabled',
			label: 'Disabled',
			type: 'checkbox',
			defaultValue: false,
			description:
				'The disabled attribute can be set to keep a user from clicking on the form element.',
			showInPlayground: true,
		},
		{
			name: 'open',
			label: 'Open',
			type: 'checkbox',
			defaultValue: false,
			description:
				"Programmatically open the dropdown. May differ if you don't use onDropdownToggle.",
			showInPlayground: false,
		},
		{
			name: 'selected-prefix / selectedPrefix',
			label: 'Selected Prefix',
			type: 'text',
			defaultValue: '',
			description:
				'Optional: Prefix text announced by screen readers before the selection (e.g. "Selected").',
			showInPlayground: false,
		},
		{
			name: 'dropdown-width / dropdownWidth',
			label: 'Dropdown Width',
			type: 'select',
			defaultValue: 'fixed',
			description:
				'Changes the behavior of the dropdown with. Default: fixed 328px Auto: Based on the size of the form-field',
			options: [
				{ value: 'fixed', label: 'Fixed', default: true },
				{ value: 'auto', label: 'Auto' },
				{ value: 'full', label: 'Full' },
			],
			showInPlayground: false,
		},
		{
			name: 'search-label / searchLabel',
			label: 'Search Label',
			type: 'text',
			defaultValue: '',
			description: 'Search label',
			showInPlayground: false,
		},
		{
			name: 'search-placeholder / searchPlaceholder',
			label: 'Search Placeholder',
			type: 'text',
			defaultValue: '',
			description: 'Search placeholder',
			showInPlayground: false,
		},
		{
			name: 'list-label / listLabel',
			label: 'List Label',
			type: 'text',
			defaultValue: '',
			description: 'Overwrite the default aria-label (props.label) for the custom-select-list',
			showInPlayground: false,
		},
		{
			name: 'loading-text / loadingText',
			label: 'Loading Text',
			type: 'text',
			defaultValue: '',
			description: 'Dropdown - hint if data has to be loaded',
			showInPlayground: false,
		},
		{
			name: 'no-results-text / noResultsText',
			label: 'No Results Text',
			type: 'text',
			defaultValue: '',
			description: 'Dropdown - hint if there are no options',
			showInPlayground: false,
		},
		{
			name: 'mobile-close-button-text / mobileCloseButtonText',
			label: 'Mobile Close Button Text',
			type: 'text',
			defaultValue: '',
			description: 'Change the button text for mobile close',
			showInPlayground: false,
		},
		{
			name: 'show-clear-selection / showClearSelection',
			label: 'Show Clear Selection',
			type: 'checkbox',
			defaultValue: true,
			description:
				'Show clear selection button (default:true). Hide it if you have very small inputs e.g. in tables.',
			showInPlayground: false,
		},
		{
			name: 'clear-selection-text / clearSelectionText',
			label: 'Clear Selection Text',
			type: 'text',
			defaultValue: '',
			description: 'Label for the clear selection button',
			showInPlayground: false,
		},
		{
			name: 'placeholder',
			label: 'Placeholder',
			type: 'text',
			defaultValue: 'Placeholder',
			description: 'Text that appears in the form control when it has no value set',
			showInPlayground: true,
		},
		{
			name: 'message-icon / messageIcon',
			label: 'Message Icon',
			type: 'text',
			defaultValue: '',
			description: 'Set/overwrite icon for helper message for form components',
			showInPlayground: false,
		},
	],
};
