export const infotextConfig = {
	elementId: 'demo-infotext',
	defaultText: 'This is helpful information',
	defaultProps: {
		id: 'demo-infotext',
		semantic: 'informational',
		size: 'small',
		showIcon: true,
	},
	slots: [
		{
			name: 'children',
			description: 'default slot',
		},
	],
	properties: [
		{
			name: 'text',
			label: 'Text',
			type: 'text',
			defaultValue: 'This is helpful information',
			description: 'Alternative for default slot/children',
			showInPlayground: true,
		},
		{
			name: 'semantic',
			label: 'Semantic',
			type: 'select',
			defaultValue: 'informational',
			description: 'The semantic defines the default variants for most components',
			options: [
				{ value: 'adaptive', label: 'Adaptive' },
				{ value: 'neutral', label: 'Neutral' },
				{ value: 'critical', label: 'Critical' },
				{ value: 'informational', label: 'Informational', default: true },
				{ value: 'warning', label: 'Warning' },
				{ value: 'successful', label: 'Successful' },
			],
			showInPlayground: true,
		},
		{
			name: 'size',
			label: 'Size',
			type: 'select',
			defaultValue: 'small',
			description: 'The size attribute changes the font-size and other related sizes of the component',
			options: [
				{ value: 'small', label: 'Small', default: true },
				{ value: 'medium', label: 'Medium' },
			],
			showInPlayground: true,
		},
		{
			name: 'show-icon / showIcon',
			label: 'Show Icon',
			type: 'checkbox',
			defaultValue: true,
			description: 'Enables or disables the visibility of the icon',
			showInPlayground: true,
		},
		{
			name: 'icon',
			label: 'Icon',
			type: 'text',
			defaultValue: '',
			description: 'Define an icon by its identifier to get displayed in front of the elements content',
			showInPlayground: false,
		},
		{
			name: 'id',
			label: 'ID',
			type: 'text',
			defaultValue: '',
			description: 'ID of the component',
			showInPlayground: false,
		},
		{
			name: 'className',
			label: 'Class Name',
			type: 'text',
			defaultValue: '',
			description: 'React specific for adding className to the component',
			showInPlayground: false,
		},
	],
};
