export const inputConfig = {
	elementId: 'playground-input',
	defaultProps: {
		label: 'Label',
		placeholder: 'Placeholder',
		type: 'text',
	},
	properties: [
		{
			name: 'id',
			label: 'ID',
			type: 'text',
			defaultValue: '',
			description:
				'ID of the component, generated automatically for some components as a fallback if unset.',
			showInPlayground: false,
		},
		{
			name: 'invalidMessage',
			alternativeName: 'invalid-message',
			label: 'Invalid Message',
			type: 'text',
			defaultValue: '',
			description: 'Helper message for invalid form components',
			showInPlayground: true,
		},
		{
			name: 'data-list-id',
			alternativeName: 'dataListId',
			label: 'Data List ID',
			type: 'text',
			defaultValue: '',
			description: "Add a custom id to data list if you're using dataList attribute.",
			showInPlayground: false,
		},
		{
			name: 'message',
			label: 'Message',
			type: 'text',
			defaultValue: '',
			description: 'Optional helper message for form components',
			showInPlayground: false,
		},
		{
			name: 'show-message',
			alternativeName: 'showMessage',
			label: 'Show Message',
			type: 'checkbox',
			defaultValue: false,
			description: 'Enables or disables the visibility of the message.',
			showInPlayground: false,
		},
		{
			name: 'value',
			label: 'Value',
			type: 'text',
			defaultValue: '',
			description: 'The value property is to receive results from the native form element.',
			showInPlayground: false,
		},
		{
			name: 'validMessage',
			alternativeName: 'valid-message',
			label: 'Valid Message',
			type: 'text',
			defaultValue: '',
			description: 'Helper message for valid form components',
			showInPlayground: true,
		},
		{
			name: 'validation',
			label: 'Validation',
			type: 'select',
			description: 'Marks an input element as invalid (red) / valid (green) / no-validation (grey)',
			options: [
				{ value: 'invalid', label: 'Invalid' },
				{ value: 'valid', label: 'Valid' },
				{ value: 'no-validation', label: 'No Validation', default: true },
			],
		},
		{
			name: 'required',
			label: 'Required',
			type: 'checkbox',
			defaultValue: false,
			description:
				'When the required attribute specified, the user will be required to fill the form element before submitting the form.',
		},
		{
			name: 'min-length',
			alternativeName: 'minLength',
			label: 'Min Length',
			type: 'text',
			defaultValue: '',
			description: 'Minimum length (number of characters) of value',
			showInPlayground: false,
		},
		{
			name: 'max-length',
			alternativeName: 'maxLength',
			label: 'Max Length',
			type: 'text',
			defaultValue: '',
			description: 'Maximum length (number of characters) of value',
			showInPlayground: false,
		},
		{
			name: 'pattern',
			label: 'Pattern',
			type: 'text',
			defaultValue: '',
			description: 'Pattern the value must match to be valid',
			showInPlayground: false,
		},
		{
			name: 'className',
			label: 'Class Name',
			type: 'text',
			defaultValue: '',
			description: 'React specific for adding className to the component.',
			showInPlayground: false,
		},
		{
			name: 'variant',
			label: 'Variant',
			type: 'select',
			description: 'Change the variant of the label to float or hidden',
			options: [
				{ value: 'above', label: 'Above', default: true },
				{ value: 'floating', label: 'Floating' },
			],
		},
		{
			name: 'show-label',
			alternativeName: 'showLabel',
			label: 'Show Label',
			type: 'checkbox',
			defaultValue: false,
			description: 'Enables/disables the visibility of the label',
			showInPlayground: false,
		},
		{
			name: 'show-icon-leading',
			alternativeName: 'showIconLeading',
			label: 'Show Icon Leading',
			type: 'checkbox',
			defaultValue: false,
			description: 'Enables or disables the visibility of the leading icon.',
			showInPlayground: false,
		},
		{
			name: 'show-icon',
			alternativeName: 'showIcon',
			label: 'Show Icon',
			type: 'checkbox',
			defaultValue: false,
			description: 'Enables or disables the visibility of the icon.',
			showInPlayground: false,
		},
		{
			name: 'icon-leading',
			alternativeName: 'iconLeading',
			label: 'Icon Leading',
			type: 'text',
			defaultValue: '',
			description:
				'Define an icon by its identifier to get displayed in front of the elements content.',
			showInPlayground: false,
		},
		{
			name: 'icon',
			label: 'Icon',
			type: 'text',
			defaultValue: '',
			description:
				'Define an icon by its identifier to get displayed in front of the elements content.',
			showInPlayground: false,
		},
		{
			name: 'icon-trailing',
			alternativeName: 'iconTrailing',
			label: 'Icon Trailing',
			type: 'text',
			defaultValue: '',
			description:
				'Define an icon by its identifier to get displayed in front of the elements content.',
			showInPlayground: false,
		},
		{
			name: 'show-required-asterisk',
			alternativeName: 'showRequiredAsterisk',
			label: 'Show Required Asterisk',
			type: 'checkbox',
			defaultValue: false,
			description:
				"This attribute allows to specify whether a form field which is marked as required will show a visual indicator (an asterisk '*').",
			showInPlayground: false,
		},
		{
			name: 'show-icon-trailing',
			alternativeName: 'showIconTrailing',
			label: 'Show Icon Trailing',
			type: 'checkbox',
			defaultValue: false,
			description: 'Enables or disables the visibility of the trailing icon.',
			showInPlayground: false,
		},
		{
			name: 'label',
			label: 'Label',
			type: 'text',
			defaultValue: 'Label',
			description: 'The label attribute specifies the caption of the form element.',
			showInPlayground: true,
		},
		{
			name: 'field-sizing',
			alternativeName: 'fieldSizing',
			label: 'Field Sizing',
			type: 'select',
			description: 'Adds shrinkwrap for input and textarea',
			options: [
				{ value: 'fixed', label: 'Fixed', default: true },
				{ value: 'content', label: 'Content' },
			],
			showInPlayground: false,
		},
		{
			name: 'name',
			label: 'Name',
			type: 'text',
			defaultValue: '',
			description:
				"The name attribute gives the name of the form control, as used in form submission and in the form element's elements object.",
			showInPlayground: false,
		},
		{
			name: 'type',
			label: 'Type',
			type: 'select',
			description: 'Type of form control',
			options: [
				{ value: 'text', label: 'Text', default: true },
				{ value: 'color', label: 'Color' },
				{ value: 'date', label: 'Date' },
				{ value: 'datetime-local', label: 'Datetime Local' },
				{ value: 'email', label: 'Email' },
				{ value: 'file', label: 'File' },
				{ value: 'hidden', label: 'Hidden' },
				{ value: 'month', label: 'Month' },
				{ value: 'number', label: 'Number' },
				{ value: 'password', label: 'Password' },
				{ value: 'range', label: 'Range' },
				{ value: 'search', label: 'Search' },
				{ value: 'tel', label: 'Tel' },
				{ value: 'time', label: 'Time' },
				{ value: 'url', label: 'URL' },
				{ value: 'week', label: 'Week' },
			],
		},
		{
			name: 'multiple',
			label: 'Multiple',
			type: 'checkbox',
			defaultValue: false,
			description: 'Allow selecting multiple files.',
			showInPlayground: false,
		},
		{
			name: 'accept',
			label: 'Accept',
			type: 'text',
			defaultValue: '',
			description: 'Specifies the types of files that the server accepts (for type="file").',
			showInPlayground: false,
		},
		{
			name: 'placeholder',
			label: 'Placeholder',
			type: 'text',
			defaultValue: 'Placeholder',
			description: 'Text that appears in the form control when it has no value set',
			showInPlayground: true,
		},
		{
			name: 'disabled',
			label: 'Disabled',
			type: 'checkbox',
			defaultValue: false,
			description:
				'The disabled attribute can be set to keep a user from clicking on the form element.',
			showInPlayground: true,
		},
		{
			name: 'step',
			label: 'Step',
			type: 'text',
			defaultValue: '',
			description: 'Sets step value.',
			showInPlayground: false,
		},
		{
			name: 'maxlength',
			label: 'Maxlength',
			type: 'text',
			defaultValue: '',
			description: 'Maximum length (number of characters) of value',
			showInPlayground: false,
		},
		{
			name: 'minlength',
			label: 'Minlength',
			type: 'text',
			defaultValue: '',
			description: 'Minimum length (number of characters) of value',
			showInPlayground: false,
		},
		{
			name: 'max',
			label: 'Max',
			type: 'text',
			defaultValue: '',
			description: 'Maximum value',
			showInPlayground: false,
		},
		{
			name: 'min',
			label: 'Min',
			type: 'text',
			defaultValue: '',
			description: 'Minimum value',
			showInPlayground: false,
		},
		{
			name: 'read-only',
			alternativeName: 'readOnly',
			label: 'Read Only',
			type: 'checkbox',
			defaultValue: false,
			description: 'The disabled attribute can be set to keep a user from edit on the form element',
			showInPlayground: false,
		},
		{
			name: 'readonly',
			label: 'Readonly',
			type: 'checkbox',
			defaultValue: false,
			description: 'The disabled attribute can be set to keep a user from edit on the form element',
			showInPlayground: false,
		},
		{
			name: 'form',
			label: 'Form',
			type: 'text',
			defaultValue: '',
			description: 'Associates the control with a form element',
			showInPlayground: false,
		},
		{
			name: 'size',
			label: 'Size',
			type: 'text',
			defaultValue: '',
			description: 'Size of the control',
			showInPlayground: false,
		},
		{
			name: 'autocomplete',
			label: 'Autocomplete',
			type: 'text',
			defaultValue: '',
			description: 'See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete',
			showInPlayground: false,
		},
		{
			name: 'autofocus',
			label: 'Autofocus',
			type: 'checkbox',
			defaultValue: false,
			description: 'Before using please check for the accessibility concerns',
			showInPlayground: false,
		},
		{
			name: 'enterkeyhint',
			label: 'Enter Key Hint',
			type: 'select',
			description: 'Hint for the enter key behavior on virtual keyboards.',
			options: [
				{ value: '', label: 'None', default: true },
				{ value: 'enter', label: 'Enter' },
				{ value: 'done', label: 'Done' },
				{ value: 'go', label: 'Go' },
				{ value: 'next', label: 'Next' },
				{ value: 'previous', label: 'Previous' },
				{ value: 'search', label: 'Search' },
				{ value: 'send', label: 'Send' },
			],
			showInPlayground: false,
		},
		{
			name: 'inputmode',
			label: 'Input Mode',
			type: 'select',
			description: 'Hint for virtual keyboard selection.',
			options: [
				{ value: '', label: 'None', default: true },
				{ value: 'none', label: 'None' },
				{ value: 'text', label: 'Text' },
				{ value: 'decimal', label: 'Decimal' },
				{ value: 'numeric', label: 'Numeric' },
				{ value: 'tel', label: 'Tel' },
				{ value: 'search', label: 'Search' },
				{ value: 'email', label: 'Email' },
				{ value: 'url', label: 'URL' },
			],
			showInPlayground: false,
		},
		{
			name: 'aria-described-by',
			label: 'Aria Described By',
			type: 'text',
			defaultValue: '',
			description: 'Overwrites auto handling for aria-describedby.',
			showInPlayground: false,
		},
		{
			name: 'message-size',
			label: 'Message Size',
			type: 'select',
			description: 'The size of the message infotext. Defaults to "small".',
			options: [
				{ value: 'small', label: 'Small', default: true },
				{ value: 'medium', label: 'Medium' },
			],
			showInPlayground: false,
		},
		{
			name: 'message-icon',
			label: 'Message Icon',
			type: 'text',
			defaultValue: '',
			description: 'Set/overwrite icon for helper message for form components',
			showInPlayground: false,
		},
		{
			name: 'valid-message-size',
			label: 'Valid Message Size',
			type: 'select',
			description: 'The size of the valid message infotext. Defaults to "small".',
			options: [
				{ value: 'small', label: 'Small', default: true },
				{ value: 'medium', label: 'Medium' },
			],
			showInPlayground: false,
		},
		{
			name: 'invalid-message-size',
			label: 'Invalid Message Size',
			type: 'select',
			description: 'The size of the invalid message infotext. Defaults to "small".',
			options: [
				{ value: 'small', label: 'Small', default: true },
				{ value: 'medium', label: 'Medium' },
			],
			showInPlayground: false,
		},
	],
};
