export const radioConfig = {
	elementId: 'playground-radio',
	defaultProps: {
		checked: false,
	},
	properties: [
		{
			name: 'id',
			type: 'text',
			label: 'ID',
			description: 'ID of the component, generated automatically for some components as a fallback if unset.',
			defaultValue: '',
			showInPlayground: false,
		},
		{
			name: 'checked',
			label: 'Checked',
			type: 'checkbox',
			defaultValue: false,
			description: 'Define the radio or checkbox elements checked state',
			showInPlayground: true,
		},
		{
			name: 'size',
			label: 'Size',
			type: 'select',
			description: 'The size attribute changes the font-size and other related sizes of the component.',
			options: [
				{ value: 'small', label: 'Small' },
				{ value: 'medium', label: 'Medium', default: true },
			],
			showInPlayground: true,
		},
		{
			name: 'show-label',
			alternativeName: 'showLabel',
			label: 'Show Label',
			type: 'checkbox',
			defaultValue: true,
			description: 'Enables/disables the visibility of the label',
			showInPlayground: true,
		},
		{
			name: 'show-required-asterisk',
			alternativeName: 'showRequiredAsterisk',
			label: 'Show Required Asterisk',
			type: 'checkbox',
			defaultValue: false,
			description: "This attribute allows to specify whether a form field which is marked as required will show a visual indicator (an asterisk '*'). It allows to prevent adding the visual indicator but still keep the field semantically required by setting its value to false. By default, its value is true, so the asterisk is shown when required is set.",
			showInPlayground: false,
		},
		{
			name: 'className',
			type: 'text',
			label: 'Class Name',
			description: 'React specific for adding className to the component.',
			defaultValue: '',
			showInPlayground: false,
		},
		{
			name: 'validation',
			label: 'Validation',
			type: 'select',
			description: "Marks an input element as invalid (red) / valid (green) / no-validation (grey). Overwrites the :user-valid selector.",
			options: [
				{ value: 'invalid', label: 'Invalid' },
				{ value: 'valid', label: 'Valid' },
				{ value: 'no-validation', label: 'No Validation', default: true },
			],
			showInPlayground: false,
		},
		{
			name: 'name',
			type: 'text',
			label: 'Name',
			description: "The name attribute gives the name of the form control, as used in form submission and in the form element's elements object.",
			defaultValue: '',
			showInPlayground: false,
		},
		{
			name: 'disabled',
			label: 'Disabled',
			type: 'checkbox',
			defaultValue: false,
			description: 'The disabled attribute can be set to keep a user from clicking on the form element.',
			showInPlayground: true,
		},
		{
			name: 'value',
			type: 'text',
			label: 'Value',
			description: 'The value property is to receive results from the native form element.',
			defaultValue: '',
			showInPlayground: false,
		},
		{
			name: 'required',
			label: 'Required',
			type: 'checkbox',
			defaultValue: false,
			description: "When the required attribute specified, the user will be required to fill the form element before submitting the form. The form element will be marked semantically as required and by default also visually with an asterisk '*' next to the label (unless the property showRequiredAsterisk is also set with the value false).",
			showInPlayground: false,
		},
		{
			name: 'label',
			label: 'Label',
			type: 'text',
			defaultValue: 'Option 1',
			description: 'The label attribute specifies the caption of the form element.',
			showInPlayground: true,
		},
	],
};
