export const textareaConfig = {
	elementId: 'playground-textarea',
	defaultText: '',
	defaultProps: {
		id: 'playground-textarea',
		label: 'Message',
		placeholder: 'Enter your message',
		variant: 'above',
	},
	slots: [
		{
			name: 'children',
			description: 'default slot',
		},
	],
	events: [
		{
			name: 'input / onInput',
			type: '---',
		},
		{
			name: 'change / onChange',
			type: '---',
		},
		{
			name: 'blur / onBlur',
			type: '---',
		},
		{
			name: 'focus / onFocus',
			type: '---',
		},
	],
	properties: [
		{
			name: 'label',
			label: 'Label',
			type: 'text',
			defaultValue: 'Message',
			description: 'The label attribute specifies the caption of the form element.',
			showInPlayground: true,
		},
		{
			name: 'placeholder',
			label: 'Placeholder',
			type: 'text',
			defaultValue: 'Enter your message',
			description: 'Text that appears in the form control when it has no value set',
			showInPlayground: true,
		},
		{
			name: 'variant',
			label: 'Variant',
			type: 'select',
			defaultValue: 'above',
			description: 'Change the variant of the label to float or hidden',
			options: [
				{ value: 'above', label: 'Above', default: true },
				{ value: 'floating', label: 'Floating' },
			],
			showInPlayground: true,
		},
		{
			name: 'resize',
			label: 'Resize',
			type: 'select',
			defaultValue: 'none',
			description: 'Control textarea resizing behavior',
			options: [
				{ value: 'none', label: 'None', default: true },
				{ value: 'both', label: 'Both' },
				{ value: 'horizontal', label: 'Horizontal' },
				{ value: 'vertical', label: 'Vertical' },
			],
			showInPlayground: true,
		},
		{
			name: 'validation',
			label: 'Validation',
			type: 'select',
			defaultValue: 'no-validation',
			description: 'Marks an input element as invalid (red) / valid (green) / no-validation (grey)',
			options: [
				{ value: 'no-validation', label: 'No Validation', default: true },
				{ value: 'valid', label: 'Valid' },
				{ value: 'invalid', label: 'Invalid' },
			],
			showInPlayground: true,
		},
		{
			name: 'invalid-message / invalidMessage',
			label: 'Invalid Message',
			type: 'text',
			defaultValue: 'Please enter a valid message',
			description: 'Helper message for invalid form components',
			showInPlayground: true,
		},
		{
			name: 'valid-message / validMessage',
			label: 'Valid Message',
			type: 'text',
			defaultValue: 'Valid input',
			description: 'Helper message for valid form components',
			showInPlayground: true,
		},
		{
			name: 'disabled',
			label: 'Disabled',
			type: 'checkbox',
			defaultValue: false,
			description:
				'The disabled attribute can be set to keep a user from clicking on the form element.',
			showInPlayground: true,
		},
		{
			name: 'required',
			label: 'Required',
			type: 'checkbox',
			defaultValue: false,
			description:
				'When the required attribute specified, the user will be required to fill the form element before submitting the form.',
			showInPlayground: true,
		},
		{
			name: 'field-sizing / fieldSizing',
			label: 'Field Sizing',
			type: 'select',
			defaultValue: 'fixed',
			description: 'Adds shrinkwrap for textarea (Note: Only supported in Chromium browsers)',
			options: [
				{ value: 'fixed', label: 'Fixed', default: true },
				{ value: 'content', label: 'Content' },
			],
			showInPlayground: false,
		},
		{
			name: 'show-label / showLabel',
			label: 'Show Label',
			type: 'checkbox',
			defaultValue: true,
			description: 'Enables/disables the visibility of the label',
			showInPlayground: false,
		},
		{
			name: 'show-required-asterisk / showRequiredAsterisk',
			label: 'Show Required Asterisk',
			type: 'checkbox',
			defaultValue: true,
			description: 'Show visual indicator (asterisk) for required fields',
			showInPlayground: false,
		},
		{
			name: 'show-resizer / showResizer',
			label: 'Show Resizer',
			type: 'checkbox',
			defaultValue: true,
			description: 'Show/Hides drag handle in the right-hand corner',
			showInPlayground: false,
		},
		{
			name: 'read-only / readOnly',
			label: 'Read Only',
			type: 'checkbox',
			defaultValue: false,
			description: 'The disabled attribute can be set to keep a user from edit on the form element',
			showInPlayground: false,
		},
		{
			name: 'value',
			label: 'Value',
			type: 'text',
			defaultValue: '',
			description: 'The value property is to receive results from the native form element.',
			showInPlayground: false,
		},
		{
			name: 'message',
			label: 'Message',
			type: 'text',
			defaultValue: '',
			description: 'Optional helper message for form components',
			showInPlayground: false,
		},
		{
			name: 'show-message / showMessage',
			label: 'Show Message',
			type: 'checkbox',
			defaultValue: false,
			description: 'Enables or disables the visibility of the message.',
			showInPlayground: false,
		},
		{
			name: 'min-length / minLength',
			label: 'Min Length',
			type: 'text',
			defaultValue: '',
			description: 'Minimum length (number of characters) of value',
			showInPlayground: false,
		},
		{
			name: 'max-length / maxLength',
			label: 'Max Length',
			type: 'text',
			defaultValue: '',
			description: 'Maximum length (number of characters) of value',
			showInPlayground: false,
		},
		{
			name: 'rows',
			label: 'Rows',
			type: 'text',
			defaultValue: '',
			description: 'The number of visible text lines for the control',
			showInPlayground: false,
		},
		{
			name: 'cols',
			label: 'Cols',
			type: 'text',
			defaultValue: '',
			description: 'The visible width of the text control, in average character widths',
			showInPlayground: false,
		},
		{
			name: 'id',
			label: 'ID',
			type: 'text',
			defaultValue: '',
			description: 'ID of the component',
			showInPlayground: false,
		},
		{
			name: 'className',
			label: 'Class Name',
			type: 'text',
			defaultValue: '',
			description: 'React specific for adding className to the component',
			showInPlayground: false,
		},
	],
};
