export const tooltipConfig = {
	elementId: 'demo-tooltip',
	defaultText: 'Tooltip söfk ösfkj ösflkj sölfkj söflsdk fölsdkjf sldkjf',
	defaultProps: {
		id: 'demo-tooltip',
		placement: 'top',
		animation: true,
		showArrow: true,
		emphasis: 'weak',
		width: 'auto',
	},
	slots: [
		{
			name: 'children',
			description: 'default slot',
		},
	],
	properties: [
		{
			name: 'text',
			label: 'Text',
			type: 'text',
			defaultValue: 'Tooltip',
			description: 'The text content of the tooltip',
			showInPlayground: true,
		},
		{
			name: 'placement',
			label: 'Placement',
			type: 'select',
			defaultValue: 'top',
			description:
				'The placement attributes values change the position to absolute and adds a transform based on the placement.',
			options: [
				{ value: 'top', label: 'Top', default: true },
				{ value: 'top-start', label: 'Top Start', noArrow: true },
				{ value: 'top-end', label: 'Top End', noArrow: true },
				{ value: 'bottom', label: 'Bottom' },
				{ value: 'bottom-start', label: 'Bottom Start', noArrow: true },
				{ value: 'bottom-end', label: 'Bottom End', noArrow: true },
				{ value: 'left', label: 'Left' },
				{ value: 'left-start', label: 'Left Start', noArrow: true },
				{ value: 'left-end', label: 'Left End', noArrow: true },
				{ value: 'right', label: 'Right' },
				{ value: 'right-start', label: 'Right Start', noArrow: true },
				{ value: 'right-end', label: 'Right End', noArrow: true },
			],
			showInPlayground: true,
		},
		{
			name: 'emphasis',
			label: 'Emphasis',
			type: 'select',
			defaultValue: 'weak',
			description: 'The emphasis attribute divides in between a weak or strong importance.',
			options: [
				{ value: 'weak', label: 'Weak', default: true },
				{ value: 'strong', label: 'Strong' },
			],
			showInPlayground: true,
		},
		{
			name: 'width',
			label: 'Width',
			type: 'select',
			defaultValue: 'auto',
			description: 'Use fixed with for default max-width',
			options: [
				{ value: 'auto', label: 'Auto', default: true },
				{ value: 'fixed', label: 'Fixed' },
			],
			showInPlayground: true,
		},
		{
			name: 'delay',
			label: 'Delay',
			type: 'select',
			defaultValue: 'none',
			description: 'Add a delay before showing the tooltip',
			options: [
				{ value: 'none', label: 'None', default: true },
				{ value: 'slow', label: 'Slow' },
				{ value: 'fast', label: 'Fast' },
			],
			showInPlayground: true,
		},
		{
			name: 'animation / data-animation',
			label: 'Animation',
			type: 'checkbox',
			defaultValue: true,
			description: 'Disable animation',
			showInPlayground: true,
		},
		{
			name: 'show-arrow / showArrow',
			label: 'Show Arrow',
			type: 'checkbox',
			defaultValue: true,
			description: 'Show/Hides arrow',
			showInPlayground: true,
		},
		{
			name: 'variant',
			label: 'Variant',
			type: 'select',
			defaultValue: '',
			description:
				'Change the behavior of the tooltip: description (Adds aria-describedby to parent), label (Adds aria-labelledby to parent)',
			options: [
				{ value: '', label: 'None', default: true },
				{ value: 'description', label: 'Description' },
				{ value: 'label', label: 'Label' },
			],
			showInPlayground: false,
		},
		{
			name: 'id',
			label: 'ID',
			type: 'text',
			defaultValue: '',
			description:
				'ID of the component, generated automatically for some components as a fallback if unset.',
			showInPlayground: false,
		},
		{
			name: 'className',
			label: 'Class Name',
			type: 'text',
			defaultValue: '',
			description: 'React specific for adding className to the component.',
			showInPlayground: false,
		},
	],
};
