---
name: On-PR to main

on:
  pull_request:
    branches: ['main']

permissions:
  pull-requests: write
  contents: write
  actions: read
  security-events: write

jobs:
  bot-prs:
    uses: ./.github/workflows/99-auto-handle-bot-prs.yml

  dependency-review:
    uses: ./.github/workflows/99-dependency-review.yml

  dependabot-review:
    uses: ./.github/workflows/99-dependabot-review.yml
